eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
  register-with-eureka: true
  fetch-registry: true
service-url:
  default-zone: http://localhost:8761/eureka
